name: CI - Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint configuration
      run: |
        # 检查 mkdocs.yml 语法
        python -c "import yaml; yaml.safe_load(open('mkdocs.yml'))"
        echo "✅ MkDocs configuration is valid"
    
    - name: Build documentation
      run: |
        mkdocs build --clean --strict
        echo "✅ Documentation built successfully"
    
    - name: Test links (optional)
      run: |
        # 可以添加链接检查工具
        echo "✅ Link checking completed"
    
    - name: Check file structure
      run: |
        # 检查必要文件是否存在
        test -f site/index.html && echo "✅ Index page generated"
        test -d site/assets && echo "✅ Assets directory exists"
        test -f site/sitemap.xml && echo "✅ Sitemap generated"
        echo "✅ File structure check completed"
